//! Animation files.
//!
//! * `.m3a`: MB3D's binary animation project (`TAnimationForm.LoadAni`,
//!   `SpeedButton9Click`), version 5: the animation settings, then per
//!   keyframe the sub-frame count, preview time, `TMandHeader10` and
//!   `THeaderCustomAddon`, then the keyframes' preview images.
//! * `.m3k`: a text format of this port, see [`parse_m3k`].  Keyframes
//!   either refer to parameter files (`.m3p`, `.m3s`, text parameters) or
//!   hold MB3D text parameters inline, so a `.m3k` file can be written by
//!   hand or generated by scripts.

use crate::anim::{Animation, Interpolation, Keyframe, OutputFormat};
use crate::scene::Scene;
use std::path::{Path, PathBuf};

const HEADER_SIZE: usize = 840;
const ADDON_SIZE: usize = 8 + 6 * 188;

/// A keyframe preview image (32 bit, as in the `.m3a` file).
#[derive(Clone, Debug, PartialEq)]
pub struct Preview {
    pub width: usize,
    pub height: usize,
    /// RGB, top row first
    pub rgb: Vec<u8>,
}

/// Size of a keyframe preview (`RenderPrevBMP`): 100 pixels wide or 80 high.
pub fn preview_size(width: i32, height: i32) -> (usize, usize) {
    let (w, h) = (width.max(1) as f64, height.max(1) as f64);
    let d = if w >= h * 1.25 { 100.0 / w } else { 80.0 / h };
    (((w * d).round() as usize).max(1), ((h * d).round() as usize).max(2))
}

/// A loaded animation with the notes of the parameter loader.
pub struct AnimFile {
    pub anim: Animation,
    /// Preview images by keyframe (from `.m3a` files)
    pub previews: Vec<Option<Preview>>,
    pub warnings: Vec<String>,
}

/// Loads a parameter file of any supported kind: `.m3p`, `.m3i`, MB3D text
/// parameters or a `.m3s` scene.  Returns the scene and loader notes.
pub fn load_scene(path: &Path) -> Result<(Scene, Vec<String>), String> {
    let data = std::fs::read(path).map_err(|e| format!("{}: {e}", path.display()))?;
    scene_from_bytes(&path.to_string_lossy(), data)
}

/// Like [`load_scene`] for file contents in memory (the kind is detected
/// from the name and the contents).
pub fn scene_from_bytes(name: &str, data: Vec<u8>) -> Result<(Scene, Vec<String>), String> {
    let lower = name.to_ascii_lowercase();
    let is_params = lower.ends_with(".m3p")
        || lower.ends_with(".m3i")
        || String::from_utf8_lossy(&data[..data.len().min(1 << 20)]).contains("Mandelbulb3Dv");
    if is_params {
        let (raw, _) = crate::m3p::raw_from_bytes(data, lower.ends_with(".m3i"))?;
        let m = crate::m3p::parse(&raw)?;
        Ok((m.scene, m.warnings))
    } else {
        let text = String::from_utf8(data).map_err(|_| format!("{name}: not a text scene file"))?;
        Ok((Scene::parse(&text).map_err(|e| format!("{name}: {e}"))?, Vec::new()))
    }
}

/// Loads `.m3a` or `.m3k` (by extension, or by contents).
pub fn load(path: &Path) -> Result<AnimFile, String> {
    let data = std::fs::read(path).map_err(|e| format!("{}: {e}", path.display()))?;
    let is_text = path.extension().is_some_and(|e| e.eq_ignore_ascii_case("m3k"))
        || (data.len() > 4 && i32::from_le_bytes(data[0..4].try_into().unwrap()) > 5 && std::str::from_utf8(&data).is_ok());
    let name = path.file_stem().map(|s| s.to_string_lossy().into_owned()).unwrap_or_else(|| "anim".into());
    if is_text {
        let text = String::from_utf8(data).map_err(|_| format!("{}: not a text file", path.display()))?;
        parse_m3k(&text, path.parent().unwrap_or(Path::new(".")), &name)
    } else {
        read_m3a(&data, &name)
    }
}

/// Saves by extension: `.m3a` (MB3D) or anything else as `.m3k` text.
/// Missing previews are written as empty images in `.m3a` files.
pub fn save(path: &Path, anim: &Animation, previews: &[Option<Preview>]) -> Result<(), String> {
    let data = if path.extension().is_some_and(|e| e.eq_ignore_ascii_case("m3a")) {
        write_m3a(anim, previews)
    } else {
        write_m3k(anim, path.parent()).into_bytes()
    };
    std::fs::write(path, data).map_err(|e| format!("{}: {e}", path.display()))
}

// ---------------------------------------------------------------------------
// .m3a

struct Rd<'a> {
    d: &'a [u8],
    p: usize,
}

impl Rd<'_> {
    fn bytes(&mut self, n: usize) -> Result<&[u8], String> {
        if self.p + n > self.d.len() {
            return Err("animation file is truncated".into());
        }
        let r = &self.d[self.p..self.p + n];
        self.p += n;
        Ok(r)
    }
    fn i32(&mut self) -> Result<i32, String> {
        Ok(i32::from_le_bytes(self.bytes(4)?.try_into().unwrap()))
    }
}

/// `LoadAni`
pub fn read_m3a(data: &[u8], name: &str) -> Result<AnimFile, String> {
    let mut r = Rd { d: data, p: 0 };
    let version = r.i32()?;
    if version > 5 {
        return Err(format!("animation file version {version} is newer than supported (5)"));
    }
    if version < 5 {
        return Err(format!(
            "animation file version {version} (MB3D before 1.7, old header format) is not supported; \
             load and save it once with a newer MB3D"
        ));
    }
    let mut a = Animation { name: name.to_string(), ..Default::default() };
    a.width = r.i32()?;
    a.height = r.i32()?;
    a.scale = r.i32()?.clamp(1, 16) as u32;
    let _calc3d = r.i32()?;
    let s = r.bytes(256)?;
    let n = (s[0] as usize).min(255);
    a.output_folder = s[1..1 + n].iter().map(|&c| c as char).collect();
    let opt = r.i32()?;
    a.interpolation = if opt & 3 == 0 { Interpolation::Linear } else { Interpolation::Bezier };
    a.looped = opt & 4 != 0;
    a.format = match (opt >> 3) & 7 {
        0 => OutputFormat::Bmp,
        2 => OutputFormat::Jpg,
        3 => OutputFormat::M3p,
        _ => OutputFormat::Png,
    };
    a.stereo_bits = (opt as u32) & 0xC0;
    a.overwrite = opt & 256 == 0;
    a.save_depth = opt & 512 != 0;
    let hc = r.i32()?;
    if !(1..=4095).contains(&hc) {
        return Err(format!("animation file: bad keyframe count {hc}"));
    }
    let mut warnings = Vec::new();
    for i in 0..hc as usize {
        let frames = r.i32()?.max(0) as u32;
        let time_ms = r.i32()?;
        let smooth = r.i32()?;
        let mut raw = r.bytes(HEADER_SIZE)?.to_vec();
        let addon = r.bytes(ADDON_SIZE)?;
        if !(16..=99).contains(&addon[0]) {
            return Err("animation file: keyframe formulas in the old format are not supported".into());
        }
        raw.extend_from_slice(addon);
        let m = crate::m3p::parse(&raw).map_err(|e| format!("keyframe {}: {e}", i + 1))?;
        for w in m.warnings {
            let w = format!("keyframe {}: {w}", i + 1);
            if !warnings.contains(&w) {
                warnings.push(w);
            }
        }
        a.keyframes.push(Keyframe { scene: m.scene, frames, time_ms, smooth, source: None });
    }
    let mut previews = Vec::new();
    for _ in 0..hc {
        let (w, h) = match (r.i32(), r.i32()) {
            (Ok(w), Ok(h)) => (w.max(0) as usize, h.max(0) as usize),
            _ => break,
        };
        let Ok(px) = r.bytes(w * h * 4) else { break };
        let mut rgb = vec![0u8; w * h * 3];
        // rows are stored bottom up, pixels as $00RRGGBB
        for y in 0..h {
            let src = &px[(h - 1 - y) * w * 4..(h - y) * w * 4];
            for x in 0..w {
                rgb[(y * w + x) * 3..(y * w + x) * 3 + 3].copy_from_slice(&[src[x * 4 + 2], src[x * 4 + 1], src[x * 4]]);
            }
        }
        previews.push((w > 0 && h > 0).then_some(Preview { width: w, height: h, rgb }));
    }
    previews.resize(hc as usize, None);
    Ok(AnimFile { anim: a, previews, warnings })
}

/// `SpeedButton9Click` (save animation), version 5.
pub fn write_m3a(a: &Animation, previews: &[Option<Preview>]) -> Vec<u8> {
    let mut d = Vec::new();
    let i32w = |d: &mut Vec<u8>, v: i32| d.extend_from_slice(&v.to_le_bytes());
    i32w(&mut d, 5);
    i32w(&mut d, a.width);
    i32w(&mut d, a.height);
    i32w(&mut d, a.scale as i32);
    i32w(&mut d, 1);
    let mut s = [0u8; 256];
    let folder: Vec<u8> = a.output_folder.chars().map(|c| if (c as u32) < 256 { c as u8 } else { b'_' }).take(255).collect();
    s[0] = folder.len() as u8;
    s[1..1 + folder.len()].copy_from_slice(&folder);
    d.extend_from_slice(&s);
    let opt = (a.interpolation as i32)
        | (a.looped as i32) << 2
        | (a.format as i32) << 3
        | (a.stereo_bits & 0xC0) as i32
        | (!a.overwrite as i32) << 8
        | (a.save_depth as i32) << 9;
    i32w(&mut d, opt);
    i32w(&mut d, a.keyframes.len() as i32);
    for k in &a.keyframes {
        i32w(&mut d, k.frames as i32);
        i32w(&mut d, k.time_ms);
        i32w(&mut d, k.smooth);
        // InsertAniWidHei: the keyframes have the animation size * scale
        let mut sc = k.scene.clone();
        sc.width = a.width * a.scale as i32;
        sc.height = a.height * a.scale as i32;
        sc.tiling = None;
        let mut raw = crate::m3p::write(&sc);
        raw[189] = a.scale.min(255) as u8; // bImageScale
        raw.resize(HEADER_SIZE + ADDON_SIZE, 0);
        d.extend_from_slice(&raw);
    }
    for i in 0..a.keyframes.len() {
        match previews.get(i).and_then(|p| p.as_ref()) {
            Some(p) => {
                i32w(&mut d, p.width as i32);
                i32w(&mut d, p.height as i32);
                for y in (0..p.height).rev() {
                    for x in 0..p.width {
                        let c = &p.rgb[(y * p.width + x) * 3..(y * p.width + x) * 3 + 3];
                        d.extend_from_slice(&[c[2], c[1], c[0], 0]);
                    }
                }
            }
            None => {
                i32w(&mut d, 0);
                i32w(&mut d, 0);
            }
        }
    }
    d
}

// ---------------------------------------------------------------------------
// .m3k text format

/// Parses the text format:
///
/// ```text
/// # mb3d animation
/// width = 640
/// height = 480
/// scale = 1              # frames are calculated this many times larger
/// interpolation = bezier # or linear
/// loop = false
/// output = frames        # folder of the frames (relative to this file)
/// name = flight          # frame files: frames/flight000001.png ...
/// format = png           # png, bmp, m3p (parameter files)
/// start_index = 1
/// index_step = 1
/// overwrite = true
/// save_depth = false
///
/// [keyframe]
/// frames = 50            # sub-frames to the next keyframe
/// file = start.m3p       # relative to this file (.m3p, .m3s, text parameters)
/// set = iterations = 40  # overrides on top (repeatable)
///
/// [keyframe]
/// frames = 50
/// params = Mandelbulb3Dv18{
/// ...
/// }
/// ```
pub fn parse_m3k(text: &str, base_dir: &Path, name: &str) -> Result<AnimFile, String> {
    let mut a = Animation { name: name.to_string(), ..Default::default() };
    let mut size_set = false;
    let mut warnings = Vec::new();
    struct Pending {
        frames: Option<u32>,
        scene: Option<Scene>,
        source: Option<String>,
        sets: Vec<String>,
        time_ms: i32,
        line: usize,
    }
    let mut keys: Vec<Pending> = Vec::new();
    let mut lines = text.lines().enumerate().peekable();
    while let Some((ln, raw)) = lines.next() {
        let line = raw.trim();
        if line.is_empty() || line.starts_with('#') || line.starts_with(';') || line.starts_with("//") {
            continue;
        }
        let err = |m: String| format!("line {}: {m}", ln + 1);
        let section = if line.starts_with('[') { line.split(['#', ';']).next().unwrap_or(line).trim() } else { line };
        if section.eq_ignore_ascii_case("[keyframe]") {
            keys.push(Pending { frames: None, scene: None, source: None, sets: Vec::new(), time_ms: 0, line: ln + 1 });
            continue;
        }
        if line.starts_with('[') {
            return Err(err(format!("unknown section {section}")));
        }
        let Some((k, v)) = line.split_once('=') else {
            return Err(err(format!("expected key = value, got '{line}'")));
        };
        let k = k.trim().to_ascii_lowercase().replace('-', "_");
        let v = v.trim();
        // a value without the comment (not for set = and params =)
        let plain = |v: &str| -> String {
            let v = v.split(" #").next().unwrap_or(v);
            v.split(" ;").next().unwrap_or(v).trim().to_string()
        };
        let num = |v: &str| -> Result<i64, String> { plain(v).parse::<i64>().map_err(|_| err(format!("{k}: bad number '{v}'"))) };
        let boolean = |v: &str| -> Result<bool, String> {
            match plain(v).to_ascii_lowercase().as_str() {
                "true" | "yes" | "1" | "on" => Ok(true),
                "false" | "no" | "0" | "off" => Ok(false),
                o => Err(err(format!("{k}: expected true or false, got '{o}'"))),
            }
        };
        let nkeys = keys.len();
        if let Some(kf) = keys.last_mut() {
            match k.as_str() {
                "frames" => kf.frames = Some(num(v)?.clamp(0, 1_000_000) as u32),
                "time_ms" => kf.time_ms = num(v)? as i32,
                "set" => kf.sets.push(v.to_string()),
                "file" => {
                    let f = plain(v);
                    let p = base_dir.join(&f);
                    let (s, w) = load_scene(&p).map_err(|e| err(e))?;
                    for w in w {
                        warnings.push(format!("{f}: {w}"));
                    }
                    kf.scene = Some(s);
                    kf.source = Some(f);
                }
                "params" => {
                    let mut t = v.to_string();
                    while !t.contains('}') {
                        let Some((_, l)) = lines.next() else { return Err(err("params: missing '}'".into())) };
                        t.push('\n');
                        t.push_str(l.trim());
                    }
                    // an optional {Titel: ...} line belongs to the parameters
                    if let Some((_, l)) = lines.peek() {
                        if l.trim_start().starts_with("{Titel") {
                            t.push('\n');
                            t.push_str(lines.next().unwrap().1.trim());
                        }
                    }
                    let (raw, _) = crate::m3p::raw_from_text(&t).map_err(|e| err(e))?;
                    let m = crate::m3p::parse(&raw).map_err(|e| err(e))?;
                    for w in m.warnings {
                        warnings.push(format!("keyframe {nkeys}: {w}"));
                    }
                    kf.scene = Some(m.scene);
                }
                _ => return Err(err(format!("unknown keyframe key '{k}' (frames, file, params, set)"))),
            }
            continue;
        }
        match k.as_str() {
            "width" => {
                a.width = num(v)?.clamp(1, 65535) as i32;
                size_set = true;
            }
            "height" => {
                a.height = num(v)?.clamp(1, 65535) as i32;
                size_set = true;
            }
            "scale" => a.scale = num(v)?.clamp(1, 16) as u32,
            "interpolation" => {
                a.interpolation = match plain(v).to_ascii_lowercase().as_str() {
                    "linear" => Interpolation::Linear,
                    "bezier" | "quadratic bezier" | "spline" => Interpolation::Bezier,
                    o => return Err(err(format!("interpolation: '{o}' (linear or bezier)"))),
                }
            }
            "loop" => a.looped = boolean(v)?,
            "output" | "output_folder" => {
                let o = plain(v);
                a.output_folder = if o.is_empty() || Path::new(&o).is_absolute() {
                    o
                } else {
                    base_dir.join(&o).to_string_lossy().into_owned()
                };
            }
            "name" => a.name = plain(v),
            "format" => a.format = OutputFormat::parse(&plain(v)).map_err(|e| err(e))?,
            "start_index" => a.start_index = num(v)?,
            "index_step" => a.index_step = num(v)?.max(1),
            "overwrite" => a.overwrite = boolean(v)?,
            "save_depth" => a.save_depth = boolean(v)?,
            _ => return Err(err(format!("unknown animation key '{k}'"))),
        }
    }
    let default_frames = 50;
    for (i, p) in keys.into_iter().enumerate() {
        let mut s = p.scene.ok_or_else(|| format!("keyframe {} (line {}): no file = or params =", i + 1, p.line))?;
        if !p.sets.is_empty() {
            s = s.apply(&p.sets.join("\n")).map_err(|e| format!("keyframe {}: {e}", i + 1))?;
        }
        if i == 0 && !size_set {
            a.set_size_from(&s);
        }
        a.keyframes.push(Keyframe {
            scene: s,
            frames: p.frames.unwrap_or(default_frames),
            time_ms: p.time_ms,
            smooth: 1,
            source: p.source.map(|f| if p.sets.is_empty() { f } else { format!("{f}\u{0}{}", p.sets.join("\u{0}")) }),
        });
    }
    let n = a.keyframes.len();
    Ok(AnimFile { anim: a, previews: vec![None; n], warnings })
}

/// Writes the text format.  Keyframes that came from a file (and were not
/// changed since) are written as `file =` references, all others inline as
/// MB3D text parameters.  `dir` is the directory of the file being written
/// (paths are made relative to it where possible).
pub fn write_m3k(a: &Animation, dir: Option<&Path>) -> String {
    use std::fmt::Write;
    let rel = |p: &str| -> String {
        if let Some(d) = dir {
            if let Ok(r) = Path::new(p).strip_prefix(d) {
                return r.to_string_lossy().into_owned();
            }
        }
        p.to_string()
    };
    let mut t = String::new();
    let _ = writeln!(t, "# mb3d animation");
    let _ = writeln!(t, "width = {}\nheight = {}\nscale = {}", a.width, a.height, a.scale);
    let _ = writeln!(
        t,
        "interpolation = {}\nloop = {}",
        if a.interpolation == Interpolation::Linear { "linear" } else { "bezier" },
        a.looped
    );
    if !a.output_folder.is_empty() {
        let _ = writeln!(t, "output = {}", rel(&a.output_folder));
    }
    let _ = writeln!(t, "name = {}\nformat = {}", a.name, a.format.extension());
    let _ = writeln!(t, "start_index = {}\nindex_step = {}", a.start_index, a.index_step);
    let _ = writeln!(t, "overwrite = {}\nsave_depth = {}", a.overwrite, a.save_depth);
    for (i, k) in a.keyframes.iter().enumerate() {
        let _ = writeln!(t, "\n[keyframe]  # {}", i + 1);
        let _ = writeln!(t, "frames = {}", k.frames);
        match &k.source {
            Some(src) => {
                let mut parts = src.split('\u{0}');
                let _ = writeln!(t, "file = {}", parts.next().unwrap_or(""));
                for s in parts {
                    let _ = writeln!(t, "set = {s}");
                }
            }
            None => {
                let mut sc = k.scene.clone();
                sc.width = a.width;
                sc.height = a.height;
                sc.tiling = None;
                sc.light_blend = None;
                let raw = crate::m3p::write(&sc);
                let txt = crate::m3p::raw_to_text(&raw, &format!("{} keyframe {}", a.name, i + 1));
                let _ = write!(t, "params = {}", txt.replace("\r\n", "\n"));
                if !t.ends_with('\n') {
                    t.push('\n');
                }
            }
        }
    }
    t
}

/// The output folder made absolute relative to `base` (for animations
/// loaded from `.m3a` files, whose folder is MB3D's absolute Windows path).
pub fn resolve_output(a: &Animation, base: &Path) -> PathBuf {
    let o = Path::new(&a.output_folder);
    if a.output_folder.is_empty() {
        base.to_path_buf()
    } else if o.is_absolute() {
        o.to_path_buf()
    } else {
        base.join(o)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample() -> Animation {
        let mut k1 = Scene::preset("Integer Power").unwrap();
        k1.width = 320;
        k1.height = 240;
        let mut k2 = Scene::preset("Amazing Box").unwrap();
        k2.zoom = 0.4;
        k2.width = 320;
        k2.height = 240;
        Animation {
            keyframes: vec![Keyframe::new(k1, 12), Keyframe::new(k2, 30)],
            width: 320,
            height: 240,
            scale: 2,
            interpolation: Interpolation::Linear,
            looped: true,
            output_folder: "out".into(),
            name: "test".into(),
            format: OutputFormat::M3p,
            overwrite: false,
            save_depth: true,
            ..Default::default()
        }
    }

    fn same_scene(a: &Scene, b: &Scene) {
        assert_eq!(a.formulas.len(), b.formulas.len());
        assert_eq!(a.formulas[0].formula.name(), b.formulas[0].formula.name());
        assert!((a.zoom - b.zoom).abs() < 1e-12);
        assert_eq!(a.iterations, b.iterations);
        assert_eq!(a.mid, b.mid);
    }

    #[test]
    fn m3a_roundtrip() {
        let a = sample();
        let pv = Preview { width: 3, height: 2, rgb: (0..18).collect() };
        let data = write_m3a(&a, &[Some(pv.clone()), None]);
        let f = read_m3a(&data, "test").unwrap();
        let b = &f.anim;
        assert_eq!((b.width, b.height, b.scale), (320, 240, 2));
        assert_eq!(b.interpolation, Interpolation::Linear);
        assert!(b.looped && !b.overwrite && b.save_depth);
        assert_eq!(b.format, OutputFormat::M3p);
        assert_eq!(b.output_folder, "out");
        assert_eq!(b.keyframes.iter().map(|k| k.frames).collect::<Vec<_>>(), vec![12, 30]);
        // keyframes are stored at the size * scale
        assert_eq!(b.keyframes[0].scene.width, 640);
        for (x, y) in a.keyframes.iter().zip(&b.keyframes) {
            same_scene(&x.scene, &y.scene);
        }
        assert_eq!(f.previews, vec![Some(pv), None]);
    }

    #[test]
    fn m3k_roundtrip_inline() {
        let a = sample();
        let text = write_m3k(&a, None);
        let f = parse_m3k(&text, Path::new("."), "x").unwrap();
        let b = &f.anim;
        assert_eq!((b.width, b.height, b.scale, b.looped), (320, 240, 2, true));
        assert_eq!(b.name, "test");
        assert_eq!(b.keyframes.len(), 2);
        for (x, y) in a.keyframes.iter().zip(&b.keyframes) {
            same_scene(&x.scene, &y.scene);
            assert_eq!(x.frames, y.frames);
        }
        // the view matrix survives (up to the last bits of the parameter encoding)
        for (x, y) in a.keyframes.iter().zip(&b.keyframes) {
            let (mx, my) = (crate::anim::unit_vgrads(&x.scene), crate::anim::unit_vgrads(&y.scene));
            for i in 0..3 {
                for j in 0..3 {
                    assert!((mx[i][j] - my[i][j]).abs() < 1e-12);
                }
            }
        }
    }

    #[test]
    fn m3k_file_references_and_sets() {
        let dir = std::env::temp_dir().join(format!("mb3d_m3k_{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::write(dir.join("k1.m3s"), Scene::preset("Integer Power").unwrap().to_text()).unwrap();
        let text = "width = 100\nheight = 80\n[keyframe]\nframes = 7\nfile = k1.m3s\nset = iterations = 33\n[keyframe]\nfile = k1.m3s\n";
        let f = parse_m3k(text, &dir, "x").unwrap();
        assert_eq!(f.anim.keyframes[0].scene.iterations, 33);
        assert_eq!(f.anim.keyframes[0].frames, 7);
        assert_eq!(f.anim.keyframes[1].frames, 50);
        let out = write_m3k(&f.anim, Some(&dir));
        assert!(out.contains("file = k1.m3s\nset = iterations = 33\n"), "{out}");
        let g = parse_m3k(&out, &dir, "x").unwrap();
        assert_eq!(g.anim.keyframes[0].scene.iterations, 33);
        assert!(parse_m3k("[keyframe]\nframes = 3\n", &dir, "x").is_err());
        assert!(parse_m3k("bogus = 1\n", &dir, "x").is_err());
        let _ = std::fs::remove_dir_all(&dir);
    }
}
